### ISSUE TITLE
cursor.wav feels laggy

### ISSUE THREAD

**Issue by nogweii** [gade01/resource.uisounds.rapier#1]
This is more wishy-washy than I wanted, but I lack the knowledge/vocabulary to better describe it. To me, it seems like moving along the GUI is lagging. I can see the cursor moving, but then there is a delay to the corresponding sound. This disconnect of visual motion and auditory confirmation causes me a little bit uncomfortable, as one would feel trying to watch a video with desynced audio.

Looking at the waveform (lazy JS demo available at http://wavesurfer-js.org/, drag & drop the .wav onto the region) my guess is that it's because of the early silence in `cursor.wav`. I'm guessing that if it were trimmed, I wouldn't have an issue.

**Comment by nogweii** [comment]
I think my suspicions are correct. Comparing the waveform of Confluence's `cursor.wav`, which to me does not feel laggy at all, shows that it's audio plays immediately, and then tapers off into silence.

**Comment by gade01** [comment]
Thanks a lot for reporting the issue.

You are probably absolutely right.

I'm on vacation right now, but I will look at all the wav files as soon as possible. Once sorted out, I will submit the update to the official repo.

Cheers
Gade

**Comment by gade01** [comment]
I have just checked, and you're absolutely right.

I have removed startup delays from back.wav, cursor.wav, notify.wav and startup.wav in commit ac28d026bc4fb141c5e1c624aabae30437dfbc3e

This will be submitted to the official repo right away :)

Thanks again.
